# Generated by Django 3.2.5 on 2022-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=200)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='DES/files')),
                ('product_disc', models.IntegerField(max_length=3)),
                ('product_category', models.CharField(max_length=100)),
            ],
        ),
    ]
