# Generated by Django 3.2.5 on 2022-01-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DES', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='DES/files'),
        ),
    ]
